### PR TITLE
Fix OpenSSL 2 deprecation warnings

### LINKED ISSUE #466: ruby 2.4.0rc1 prints depricated warnings
```
$ ruby -v -r net/ssh -e 'Net::SSH.start("localhost"){}' 2>&1 | sort | uniq
.../net-ssh-4.0.0.rc1/lib/net/ssh/buffer.rb:258: warning: #e= is deprecated; use #set_key
.../net-ssh-4.0.0.rc1/lib/net/ssh/buffer.rb:259: warning: #n= is deprecated; use #set_key
.../net-ssh-4.0.0.rc1/lib/net/ssh/transport/cipher_factory.rb:60: warning: constant OpenSSL::Cipher::Cipher is deprecated
.../net-ssh-4.0.0.rc1/lib/net/ssh/transport/cipher_factory.rb:88: warning: constant OpenSSL::Cipher::Cipher is deprecated
.../net-ssh-4.0.0.rc1/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:118: warning: #g= is deprecated; use #set_pqg
.../net-ssh-4.0.0.rc1/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:118: warning: #p= is deprecated; use #set_pqg
.../net-ssh-4.0.0.rc1/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:119: warning: #priv_key= is deprecated; use #set_key
ruby 2.4.0rc1 (2016-12-12 trunk 57064) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by mfazekas**
Closes #466

See https://github.com/ruby/openssl/issues/93#issuecomment-267359787

### CODE REVIEW

File: lib/net/ssh/transport/cipher_factory.rb [hunk 1]
```diff
@@ -94,6 +94,15 @@ def self.get_lengths(name, options = {})
...
     end
+
+    def self.new_ossl_cipher(ossl_name)
+      if OpenSSL::Cipher.respond_to?(:new)
+        OpenSSL::Cipher.new(ossl_name)
+      else
+        OpenSSL::Cipher::Cipher.new(ossl_name)
+      end
+    end
+    private_class_method :new_ossl_cipher
```
Comment (rhenium) [inline lib/net/ssh/transport/cipher_factory.rb]: It is Ruby 1.9.0 that actually renamed OpenSSL::Cipher::Cipher to OpenSSL::Cipher. I think net-ssh no longer supports Ruby 1.8?

Comment (mfazekas) [inline lib/net/ssh/transport/cipher_factory.rb]: fixing, thanks!
